### PR TITLE
Change new workspaces title dyndesc to "Dynamic #"

### PR DESCRIPTION
**Pull request by netizen-ais**

### CODE REVIEW

**Comment by netizen-ais** [comment]
Requested at https://github.com/maurges/dynamic_workspaces/issues/10#issuecomment-1993557841 and https://github.com/maurges/dynamic_workspaces/issues/10#issuecomment-1993557841

**Comment by exincore** [comment]
`workspace.createDesktop(workspace.desktops.length, undefined)` might be a better option.

See https://github.com/maurges/dynamic_workspaces/issues/10#issuecomment-2051284370.

**Comment by netizen-ais** [comment]
> `workspace.createDesktop(workspace.desktops.length, undefined)` might be a better option.
> 
> See [#10 (comment)](https://github.com/maurges/dynamic_workspaces/issues/10#issuecomment-2051284370).

I'll keep my patch, I think it's an added value. I'll try to learn about making it configurable

**Comment by maurges** [comment]
Obsoleted by #18

**Pull request closed without merging**
